test

diff --git a/.github/workflows/5_builderpackage_dashboard.yml b/.github/workflows/5_builderpackage_dashboard.yml
--- a/.github/workflows/5_builderpackage_dashboard.yml
+++ b/.github/workflows/5_builderpackage_dashboard.yml
@@ -139,10 +139,23 @@ jobs:
       - name: Get SHA of wazuh-dashboard-plugins
         id: get-plugins-sha
         run: |
-          SHA=$(git ls-remote https://github.com/wazuh/wazuh-dashboard-plugins.git ${{ inputs.reference_plugins }} | cut -f1 | cut -c1-7)
+          REFERENCE="${{ inputs.reference_plugins }}"
+          if [ -z "$REFERENCE" ]; then
+            REFERENCE="${{ github.ref_name }}"
+          fi
 
-          if [ -z "${{ inputs.reference_plugins }}" ] || [ "$SHA" = "" ]; then
-            SHA=$(git ls-remote https://github.com/wazuh/wazuh-dashboard-plugins.git $BRANCH | cut -f1 | cut -c1-7)
+          echo "Using reference: $REFERENCE"
+          
+          SHA=$(git ls-remote https://github.com/wazuh/wazuh-dashboard-plugins.git "$REFERENCE" | cut -f1 | cut -c1-7)
+
+          if [ -z "$SHA" ]; then
+            echo "Reference $REFERENCE not found, trying with '${{ github.ref_name }}' branch"
+            SHA=$(git ls-remote https://github.com/wazuh/wazuh-dashboard-plugins.git ${{ github.ref_name }} | cut -f1 | cut -c1-7)
+          fi
+
+          if [ -z "$SHA" ]; then
+            echo "Reference ${{ github.ref_name }} not found, check if the repository exists and the reference is correct."
+            exit 1
           fi
 
           echo "WAZUH_PLUGINS_SHA=$SHA" >> $GITHUB_OUTPUT
