test

diff --git a/.github/workflows/5_builderpackage_dashboard.yml b/.github/workflows/5_builderpackage_dashboard.yml
--- a/.github/workflows/5_builderpackage_dashboard.yml
+++ b/.github/workflows/5_builderpackage_dashboard.yml
@@ -139,18 +139,19 @@ jobs:
       - name: Get SHA of wazuh-dashboard-plugins
         id: get-plugins-sha
         run: |
+          REPOSITORY=https://github.com/wazuh/wazuh-dashboard-plugins.git
           REFERENCE="${{ inputs.reference_plugins }}"
           if [ -z "$REFERENCE" ]; then
             REFERENCE="${{ github.ref_name }}"
           fi
 
           echo "Using reference: $REFERENCE"
-          
-          SHA=$(git ls-remote https://github.com/wazuh/wazuh-dashboard-plugins.git "$REFERENCE" | cut -f1 | cut -c1-7)
+
+          SHA=$(git ls-remote $REPOSITORY "$REFERENCE" | cut -f1 | cut -c1-7)
 
           if [ -z "$SHA" ]; then
             echo "Reference $REFERENCE not found, trying with '${{ github.ref_name }}' branch"
-            SHA=$(git ls-remote https://github.com/wazuh/wazuh-dashboard-plugins.git ${{ github.ref_name }} | cut -f1 | cut -c1-7)
+            SHA=$(git ls-remote $REPOSITORY ${{ github.ref_name }} | cut -f1 | cut -c1-7)
           fi
 
           if [ -z "$SHA" ]; then
@@ -163,30 +164,102 @@ jobs:
       - name: Get SHA of wazuh-security-dashboards-plugin
         id: get-security-sha
         run: |
-          git clone -b ${{ inputs.reference_plugins }} --single-branch https://github.com/wazuh/wazuh-security-dashboards-plugin.git wzsp
-          cd wzsp
-          echo "WAZUH_SECURITY_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          REPOSITORY=https://github.com/wazuh/wazuh-security-dashboards-plugin.git
+          REFERENCE="${{ inputs.reference_plugins }}"
+          if [ -z "$REFERENCE" ]; then
+            REFERENCE="${{ github.ref_name }}"
+          fi
+
+          echo "Using reference: $REFERENCE"
+
+          SHA=$(git ls-remote $REPOSITORY "$REFERENCE" | cut -f1 | cut -c1-7)
+
+          if [ -z "$SHA" ]; then
+            echo "Reference $REFERENCE not found, trying with '${{ github.ref_name }}' branch"
+            SHA=$(git ls-remote $REPOSITORY ${{ github.ref_name }} | cut -f1 | cut -c1-7)
+          fi
+
+          if [ -z "$SHA" ]; then
+            echo "Reference ${{ github.ref_name }} not found, check if the repository exists and the reference is correct."
+            exit 1
+          fi
+
+          echo "WAZUH_SECURITY_SHA=$SHA" >> $GITHUB_OUTPUT
 
       - name: Get SHA of wazuh-dashboard-reporting
         id: get-reporting-sha
         run: |
-          git clone -b ${{ inputs.reference_plugins }} --single-branch https://github.com/wazuh/wazuh-dashboard-reporting.git wzrp
-          cd wzrp
-          echo "WAZUH_REPORTING_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          REPOSITORY=https://github.com/wazuh/wazuh-dashboard-reporting.git
+          REFERENCE="${{ inputs.reference_plugins }}"
+          if [ -z "$REFERENCE" ]; then
+            REFERENCE="${{ github.ref_name }}"
+          fi
+
+          echo "Using reference: $REFERENCE"
+
+          SHA=$(git ls-remote $REPOSITORY "$REFERENCE" | cut -f1 | cut -c1-7)
+
+          if [ -z "$SHA" ]; then
+            echo "Reference $REFERENCE not found, trying with '${{ github.ref_name }}' branch"
+            SHA=$(git ls-remote $REPOSITORY ${{ github.ref_name }} | cut -f1 | cut -c1-7)
+          fi
+
+          if [ -z "$SHA" ]; then
+            echo "Reference ${{ github.ref_name }} not found, check if the repository exists and the reference is correct."
+            exit 1
+          fi
+
+          echo "WAZUH_REPORTING_SHA=$SHA" >> $GITHUB_OUTPUT
 
       - name: Get SHA of wazuh-dashboard-ml-commons
         id: get-ml-sha
         run: |
-          git clone -b ${{ inputs.reference_plugins }} --single-branch https://github.com/wazuh/wazuh-dashboard-ml-commons.git mlc
-          cd mlc
-          echo "ML_COMMONS_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          REPOSITORY=https://github.com/wazuh/wazuh-dashboard-ml-commons.git
+          REFERENCE="${{ inputs.reference_plugins }}"
+          if [ -z "$REFERENCE" ]; then
+            REFERENCE="${{ github.ref_name }}"
+          fi
+
+          echo "Using reference: $REFERENCE"
+
+          SHA=$(git ls-remote $REPOSITORY "$REFERENCE" | cut -f1 | cut -c1-7)
+
+          if [ -z "$SHA" ]; then
+            echo "Reference $REFERENCE not found, trying with '${{ github.ref_name }}' branch"
+            SHA=$(git ls-remote $REPOSITORY ${{ github.ref_name }} | cut -f1 | cut -c1-7)
+          fi
+
+          if [ -z "$SHA" ]; then
+            echo "Reference ${{ github.ref_name }} not found, check if the repository exists and the reference is correct."
+            exit 1
+          fi
+
+          echo "ML_COMMONS_SHA=$SHA" >> $GITHUB_OUTPUT
 
       - name: Get SHA of wazuh-dashboard-security-analytics
         id: get-security-analytics-sha
         run: |
-          git clone -b ${{ inputs.reference_plugins }} --single-branch https://github.com/wazuh/wazuh-dashboard-security-analytics.git wzsa
-          cd wzsa
-          echo "WAZUH_SECURITY_ANALYTICS_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+          REPOSITORY=https://github.com/wazuh/wazuh-dashboard-security-analytics.git
+          REFERENCE="${{ inputs.reference_plugins }}"
+          if [ -z "$REFERENCE" ]; then
+            REFERENCE="${{ github.ref_name }}"
+          fi
+
+          echo "Using reference: $REFERENCE"
+
+          SHA=$(git ls-remote $REPOSITORY "$REFERENCE" | cut -f1 | cut -c1-7)
+
+          if [ -z "$SHA" ]; then
+            echo "Reference $REFERENCE not found, trying with '${{ github.ref_name }}' branch"
+            SHA=$(git ls-remote $REPOSITORY ${{ github.ref_name }} | cut -f1 | cut -c1-7)
+          fi
+
+          if [ -z "$SHA" ]; then
+            echo "Reference ${{ github.ref_name }} not found, check if the repository exists and the reference is correct."
+            exit 1
+          fi
+
+          echo "WAZUH_SECURITY_ANALYTICS_SHA=$SHA" >> $GITHUB_OUTPUT
 
       - name: Setup variables
         id: setup-variables
