Generate packages smoke tests (#623)

diff --git a/.github/workflows/build_wazuh_dashboard_with_plugins.yml b/.github/workflows/build_wazuh_dashboard_with_plugins.yml
--- a/.github/workflows/build_wazuh_dashboard_with_plugins.yml
+++ b/.github/workflows/build_wazuh_dashboard_with_plugins.yml
@@ -86,6 +86,10 @@ on:
         type: string
         required: false
 
+permissions:
+  id-token: write
+  contents: read
+
 jobs:
   setup-variables:
     runs-on: ubuntu-24.04
@@ -93,6 +97,7 @@ jobs:
     outputs:
       CURRENT_DIR: ${{ steps.setup-variables.outputs.CURRENT_DIR }}
       VERSION: ${{ steps.setup-variables.outputs.VERSION }}
+      PREVIOUS: ${{ steps.setup-variables.outputs.PREVIOUS }}
       REVISION: ${{ steps.setup-variables.outputs.REVISION }}
       COMMIT_SHA: ${{ steps.setup-variables.outputs.COMMIT_SHA }}
       PLUGINS_SHA: ${{ steps.setup-variables.outputs.PLUGINS_SHA }}
@@ -133,6 +138,18 @@ jobs:
         run: |
           CURRENT_DIR=$(pwd -P)
           VERSION=$(jq -r '.version' VERSION.json)
+          # Check the corresponding previous version to be used in the upgrade test
+          PREVIOUS=$(apt-cache madison wazuh-dashboard | grep -A 1 "$VERSION" | tail -1 | awk '{print $3}')
+          if [ -z "$PREVIOUS" ]; then
+            MAJOR_MINOR=$(echo "$VERSION" | cut -d '.' -f 1,2)
+            PREVIOUS=$(apt-cache madison wazuh-dashboard | grep "$MAJOR_MINOR" | head -1 | awk '{print $3}')
+          fi
+          if [ -z "$PREVIOUS" ]; then
+            PREVIOUS=$(apt-cache madison wazuh-dashboard | head -1 | awk '{print $3}')
+          fi
+          if [ -z "$PREVIOUS" ]; then
+            echo "::warning No previous version::No previous version found for this architecture. Upgrade test will be skipped."
+          fi
           REVISION=$(yarn --silent wzd-revision)
           COMMIT_SHA=$(git rev-parse --short HEAD)
           PLUGINS_SHA=${{steps.get-plugins-sha.outputs.WAZUH_PLUGINS_SHA}}
@@ -167,6 +184,7 @@ jobs:
           fi
           echo "CURRENT_DIR=$CURRENT_DIR" >> $GITHUB_OUTPUT
           echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
+          echo "PREVIOUS=$PREVIOUS" >> $GITHUB_OUTPUT
           echo "REVISION=$REVISION" >> $GITHUB_OUTPUT
           echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_OUTPUT
           echo "PLUGINS_SHA=$PLUGINS_SHA" >> $GITHUB_OUTPUT
@@ -225,7 +243,7 @@ jobs:
     with:
       reference: ${{ inputs.reference_security_plugins }}
 
-  build-and-test-package:
+  build-package:
     needs: [setup-variables, build-main-plugins, build-base, build-security-plugin]
     runs-on: ${{ (inputs.architecture == 'arm64' || inputs.architecture == 'aarch64') && 'wz-linux-arm64' || 'ubuntu-22.04' }}
     name: Generate packages
@@ -284,14 +302,218 @@ jobs:
             --commit-sha ${{needs.setup-variables.outputs.COMMIT_SHA}}-${{needs.setup-variables.outputs.PLUGINS_SHA}}-${{needs.setup-variables.outputs.SECURITY_SHA}} \
             --${{ inputs.system }} ${{ needs.setup-variables.outputs.PRODUCTION }} --debug
 
-      - name: Test package
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        if: success()
+        with:
+          name: ${{needs.setup-variables.outputs.PACKAGE_NAME}}
+          path: ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/build-packages/output/${{needs.setup-variables.outputs.PACKAGE_NAME}}
+          retention-days: 30
+          overwrite: true
+
+      - name: Upload checksum
+        if: success() && ${{ inputs.checksum }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{needs.setup-variables.outputs.PACKAGE_NAME}}.sha512
+          path: ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/build-packages/output/${{needs.setup-variables.outputs.PACKAGE_NAME}}.sha512
+          retention-days: 30
+          overwrite: true
+
+  test-package:
+    needs: [setup-variables, build-package]
+    runs-on: ${{ needs.setup-variables.outputs.ARCHITECTURE_FLAG == '--arm' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
+    strategy:
+      fail-fast: false
+    name: Test package
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Download  artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{needs.setup-variables.outputs.PACKAGE_NAME}}
+          path: ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages
+
+      - name: Test package integrity
         run: |
           cd ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages
-          ls -laR ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/build-packages/output
-          cp ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/build-packages/output/${{needs.setup-variables.outputs.PACKAGE_NAME}}  ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages/${{ inputs.system }}
+          cp ./${{needs.setup-variables.outputs.PACKAGE_NAME}}  ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages/${{ inputs.system }}
           bash ./test-packages.sh \
             -p ${{needs.setup-variables.outputs.PACKAGE_NAME}}
 
+      - name: DEB - Test package install/uninstall
+        if: ${{ inputs.system == 'deb' }}
+        run: |
+          sudo dpkg -i ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages/${{needs.setup-variables.outputs.PACKAGE_NAME}}
+          if dpkg-query -W -f='${Status}' wazuh-dashboard 2>/dev/null | grep -q "install ok installed"; then
+            echo "Package installed"
+          else
+            echo "Package not installed"
+            exit 1
+          fi
+          sudo  systemctl daemon-reload
+          sudo  systemctl enable wazuh-dashboard
+          sudo  systemctl start wazuh-dashboard
+          if sudo systemctl status wazuh-dashboard | grep -q "active (running)"; then
+            echo "Service running"
+          else
+            echo "Service not running"
+            exit 1
+          fi
+          sudo apt-get remove --purge wazuh-dashboard -y
+          if dpkg-query -W -f='${Status}' wazuh-dashboard 2>/dev/null | grep -q "install ok installed"; then
+            echo "Package not uninstalled"
+            exit 1
+          else
+            echo "Package uninstalled"
+          fi
+
+      - name: DEB - Test package upgrade
+        if: ${{ needs.setup-variables.outputs.PREVIOUS != '' && inputs.system == 'deb' }}
+        run: |
+          sudo apt-get install debhelper tar curl libcap2-bin #debhelper version 9 or later
+          sudo apt-get install gnupg apt-transport-https
+          sudo curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | sudo gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && sudo chmod 644 /usr/share/keyrings/wazuh.gpg
+          sudo echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee -a /etc/apt/sources.list.d/wazuh.list
+          sudo apt-get update
+          sudo apt-get -y install wazuh-dashboard=${{needs.setup-variables.outputs.PREVIOUS}}
+          sudo  systemctl daemon-reload
+          sudo  systemctl enable wazuh-dashboard
+          sudo  systemctl start wazuh-dashboard
+          sudo dpkg -i ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages/${{needs.setup-variables.outputs.PACKAGE_NAME}}
+          sudo systemctl restart wazuh-dashboard
+
+          if dpkg -s wazuh-dashboard | grep '^Version:' | grep -q "${{needs.setup-variables.outputs.VERSION}}"; then
+            echo "Package upgraded"
+          else
+            echo "Package not upgraded"
+            exit 1
+          fi
+
+          if sudo systemctl status wazuh-dashboard | grep -q "active (running)"; then
+            echo "Service running"
+          else
+            echo "Service not running"
+            exit 1
+          fi
+
+      - name: RPM - Clone automation repo
+        if: ${{ inputs.system == 'rpm' }}
+        env:
+          username: 'wazuh-devel-xdrsiem-dashboard'
+        run: |
+          git clone https://${{ env.username }}:${{ secrets.DASHBOARD_BOT_SMOKE_TEST_TOKEN }}@github.com/wazuh/wazuh-automation.git
+          cd wazuh-automation
+          sudo pip3 install -r deployability/deps/requirements.txt
+
+      - name: RPM - Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        if: ${{ inputs.system == 'rpm' }}
+        with:
+          aws-region: 'us-east-1'
+          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
+          role-session-name: 'Dashboard-smoke-test'
+
+      - name: RPM - Setup environment
+        if: ${{ inputs.system == 'rpm' }}
+        run: |
+          if [ "${{ inputs.architecture }}" = "x86_64" ]; then
+            python3 wazuh-automation/deployability/modules/allocation/main.py --action create --provider aws --size large --composite-name linux-centos-9-amd64 --instance-name "centos_9_amd_large_aws" --inventory-output "/tmp/inventory.yaml" --track-output "/tmp/track.yaml" --label-team dashboard --label-termination-date 1d --working-dir /tmp/dashboard
+          else
+            python3 wazuh-automation/deployability/modules/allocation/main.py --action create --provider aws --size large --composite-name  linux-centos-8-arm64 --instance-name "centos_8_arm_large_aws" --inventory-output "/tmp/inventory.yaml" --track-output "/tmp/track.yaml" --label-team dashboard --label-termination-date 1d --working-dir /tmp/dashboard
+          fi
+          ansible_host=$(grep 'ansible_host:' /tmp/inventory.yaml | sed 's/.*: *//')
+          ansible_port=$(grep 'ansible_port:' /tmp/inventory.yaml | sed 's/.*: *//')
+          ansible_user=$(grep 'ansible_user:' /tmp/inventory.yaml | sed 's/.*: *//')
+          ansible_ssh_private_key_file=$(grep 'ansible_ssh_private_key_file:' /tmp/inventory.yaml | sed 's/.*: *//')
+          ssh_command="ssh -o StrictHostKeyChecking=no -i $ansible_ssh_private_key_file -p $ansible_port $ansible_user@$ansible_host"
+          scp_command="scp -o StrictHostKeyChecking=no -i $ansible_ssh_private_key_file -P $ansible_port"
+          echo "ansible_host=$ansible_host" >> $GITHUB_OUTPUT
+          echo "ansible_port=$ansible_port" >> $GITHUB_OUTPUT
+          echo "ansible_user=$ansible_user" >> $GITHUB_OUTPUT
+          echo "ansible_ssh_private_key_file=$ansible_ssh_private_key_file" >> $GITHUB_OUTPUT
+          echo "ssh_command=$ssh_command" >> $GITHUB_OUTPUT
+          echo "scp_command=$scp_command" >> $GITHUB_OUTPUT
+        id: setup_rpm_env
+
+      - name: RPM - Test package install/uninstall
+        if: ${{ inputs.system == 'rpm' }}
+        run: |
+          # echo 'Installing package...' is necessary to init the ssh connection prior to running scp
+          ${{ steps.setup_rpm_env.outputs.ssh_command }} "echo 'Installing package...'"
+          ${{ steps.setup_rpm_env.outputs.scp_command }} ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/test-packages/${{needs.setup-variables.outputs.PACKAGE_NAME}} ${{ steps.setup_rpm_env.outputs.ansible_user }}@${{ steps.setup_rpm_env.outputs.ansible_host }}:/home/${{ steps.setup_rpm_env.outputs.ansible_user }}/
+
+          ${{ steps.setup_rpm_env.outputs.ssh_command }} "sudo rpm -i ./${{needs.setup-variables.outputs.PACKAGE_NAME}}; \
+              if rpm -q wazuh-dashboard &>/dev/null; then \
+                echo 'Package installed'; \
+              else \
+                echo 'Package not installed'; \
+                exit 1; \
+              fi; \
+              sudo  systemctl daemon-reload;\
+              sudo  systemctl enable wazuh-dashboard;\
+              sudo  systemctl start wazuh-dashboard;\
+              if sudo systemctl status wazuh-dashboard | grep -q 'active (running)'; then \
+                echo 'Service running'; \
+              else \
+                echo 'Service not running' ;\
+                exit 1 ;\
+              fi; \
+              sudo yum remove wazuh-dashboard -y ;\
+              sudo rm -rf /var/lib/wazuh-dashboard/ ; \
+              sudo rm -rf /usr/share/wazuh-dashboard/ ; \
+              sudo rm -rf /etc/wazuh-dashboard/; \
+              if rpm -q wazuh-dashboard &>/dev/null; then \
+                echo 'Package not uninstalled'; \
+                exit 1; \
+              else \
+                echo 'Package uninstalled'; \
+              fi
+              "
+
+      - name: RPM - Test package upgrade
+        if: ${{ needs.setup-variables.outputs.PREVIOUS != '' && inputs.system == 'rpm' }}
+        run: |
+          ${{ steps.setup_rpm_env.outputs.ssh_command }} "sudo yum install libcap; \
+            sudo rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH; \
+            sudo echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages.wazuh.com/4.x/yum/\nprotect=1' | sudo tee /etc/yum.repos.d/wazuh.repo; \
+            sudo yum install -y wazuh-dashboard-${{needs.setup-variables.outputs.PREVIOUS}}; \
+            sudo  systemctl daemon-reload; \
+            sudo  systemctl enable wazuh-dashboard; \
+            sudo  systemctl start wazuh-dashboard; \
+            sudo yum install -y ${{needs.setup-variables.outputs.PACKAGE_NAME}}; \
+            sudo systemctl restart wazuh-dashboard; \
+            if rpm -q wazuh-dashboard | grep -q '${{needs.setup-variables.outputs.VERSION}}'; then \
+              echo 'Package upgraded'; \
+            else \
+              echo 'Package not upgraded'; \
+              exit 1; \
+            fi; \
+            if sudo systemctl status wazuh-dashboard | grep -q 'active (running)'; then \
+              echo 'Service running'; \
+            else \
+              echo 'Service not running'; \
+              exit 1; \
+            fi
+            "
+      - name: Destroy Allocator Machine
+        #DO NOT DELETE. This ensures that the generated instance is destroyed even if the job fails.
+        if: ${{ always() }}
+        ########################################
+        run: |
+          if [ "${{ inputs.system }}" = "rpm" ]; then
+            echo "Destroying Allocator Machine"
+            cd wazuh-automation/deployability
+            python3 modules/allocation/main.py --action delete --track-output "/tmp/track.yaml"
+          fi
+
+  upload-package:
+    needs: [setup-variables, test-package]
+    runs-on: ${{ inputs.architecture == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
+    name: Upload package
+    steps:
       - name: Set up AWS CLI
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -299,10 +521,23 @@ jobs:
           aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
           aws-region: ${{ secrets.CI_AWS_REGION }}
 
+      - name: Download  artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{needs.setup-variables.outputs.PACKAGE_NAME}}
+          path: ./
+
+      - name: Download  checksum
+        if: ${{ inputs.checksum }}
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{needs.setup-variables.outputs.PACKAGE_NAME}}.sha512
+          path: ./
+
       - name: Upload package
         run: |
           echo "Uploading package"
-          aws s3 cp  ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/build-packages/output/${{needs.setup-variables.outputs.PACKAGE_NAME}} s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/
+          aws s3 cp ./${{needs.setup-variables.outputs.PACKAGE_NAME}} s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/
           s3uri="s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/${{needs.setup-variables.outputs.PACKAGE_NAME}}"
           echo "S3 URI: ${s3uri}"
 
@@ -310,6 +545,6 @@ jobs:
         if: ${{ inputs.checksum }}
         run: |
           echo "Uploading checksum"
-          aws s3 cp ${{ needs.setup-variables.outputs.CURRENT_DIR }}/dev-tools/build-packages/output/${{needs.setup-variables.outputs.PACKAGE_NAME}}.sha512 s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/
+          aws s3 cp ./${{needs.setup-variables.outputs.PACKAGE_NAME}}.sha512 s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/
           s3uri="s3://packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/${{needs.setup-variables.outputs.PACKAGE_NAME}}.sha512"
           echo "S3 sha512 URI: ${s3uri}"
